version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=mydatabase
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
